### PR TITLE
Add OptionalField for fields which can be None

### PR DESCRIPTION
**Pull request by dbanty**

### CODE REVIEW

**Comment by cymoo** [comment]
Fields are optional by default except declared `required` explicitly. Using `OptionalField` is intuitive but may cause confusion. 

```python
class MyModel(Model):
    foo: Optional[int]
    bar: int

    class Meta:
        required = ['bar']
```

If introducing `Optional`, the feature of `required` should be removed at the same time.

**Comment by dbanty** [comment]
The issue I had that I was trying to solve was in assigning `None` to optional fields. I figured that `None` was just not supported yet, thus the addition. Maybe I was just doing something wrong.

I'll experiment and attempt to reproduce my issue in the published version (currently my project is pointing at my fork) and get back to you here.

**Comment by cymoo** [comment]
In the very early version, `None` was supported (later removed). If a field was not assigned, it would default to `None`. 

When using this lib in my projects, I found it was kind of cumbersome to deal with `None`.  If 'empty' semantics was needed, I choose to assign a 'falsy' value like `[], {}, 0`.

But maybe in some cases `None` is necessary. Please go ahead with your experiments.

**Comment by dbanty** [comment]
I played with the code a bit and I understand better how it works today. Longer explanation is below but TL;DR I would like to ability to mark a field as `Optional` so that a static type checker (mypy) will prevent me (and my fellow coders) from using it in an unsafe way.

The way it is currently, all fields are "optional" unless explicitly set as required (you said this above, I'm just restating). In the library's semantics, as is, this means you aren't required to set a value on the field, **not** that the value can be set to `None`. Instead, if you do not set the field and attempt to access it you will get a runtime exception. If you attempt to set the field to `None`, you get a different runtime exception.

In the builtin Python `typing` module, the `Optional` type indicates not that a value can be "unset" but that the value can be set to `None`. This is extremely useful for code which is statically checked with mypy as mypy will indicate when you have a potentially unsafe reference (e.g. trying to treat a value as `str` when it could be `None`).

My goal with this feature was exactly that, to be able to indicate to mypy that a field could be unset so it will warn when we use it in unsafe ways to help prevent errors. Ideally "unset" would be `None` instead of raising an exception since there are static checks for `None` and easier semantics for dealing with it (e.g. `my_model.my_optional_str or "default_string_here"` instead of `try` and `except`).

If you wish to retain the existing behavior (allowing fields to be unset when not included in `Meta.required` and raising exceptions when accessed) then perhaps `OptionalField` is a confusing name for it. Perhaps `NullableField` or `NoneableField`? I was just trying to align with the built in nomenclature.

**Comment by cymoo** [comment]
> In the library's semantics, as is, this means you aren't required to set a value on the field, not that the value can be set to None. 
You are right. Without an `Optional` field, this library could not work well with some static checker. 
Could I invite you an a collaborator?

**Comment by cymoo** [comment]
I think `OptionalField` is a better name, so `Meta.required` seems need to be removed.

**Comment by dbanty** [comment]
@cymoo I made a branch called "optional_field" in this repo now so you can more easily work on it directly. I removed references to "required" in metadata and updated some tests to use Optional fields. I fixed some issues that I found with the Optional fields in failing tests, but there are still a few more errors.

My understanding of the inner workings of the project is still pretty early. Will you take a look at that branch and help fix the tests that are still failing?

**Pull request closed without merging**
